services:
  - type: web
    name: emotion-drift-api
    env: python
    region: ohio
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONPATH
        value: "."
      - key: SARVAM_API_KEY
        sync: false # User must set this manually in Render dashboard
