import os
import json

patterns = {
    "catastrophizing": [
        "Everything is completely ruined and there is nothing I can do to fix it.",
        "I am definitely going to fail this exam and my entire future will be destroyed.",
        "If they leave me, I will be alone forever and my life won't be worth living.",
        "I made a mistake in the presentation, now everyone thinks I am completely incompetent and I'll get fired.",
        "My heart is beating fast; I must be having a heart attack and I am going to die.",
        "This minor setback means the entire project is a total failure.",
        "If I don't get this job, my career is completely over.",
        "They haven't texted back in an hour; they must hate me and want to end our friendship.",
        "I feel a slight pain in my leg; it must be a blood clot and I will lose my leg.",
        "I am never going to recover from this stress; it's just going to get worse and worse.",
        "One wrong move and everything I've built will collapse instantly.",
        "I am doomed to be unhappy for the rest of my life.",
        "This is the worst thing that could possibly happen to me.",
        "If I fail, my parents will disown me and everyone will laugh at me.",
        "There is absolutely no hope for my situation; it's completely terminal.",
        "I can't handle this; it's going to drive me crazy and destroy my mind.",
        "Everyone is going to judge me, and I will be publically humiliated.",
        "If I don't pass, I'll end up homeless and broke.",
        "A single error means I am a total fraud and everyone will find out.",
        "It's all over for me; there is no point in even trying anymore.",
        "If this relationship fails, I am unlovable and will die alone.",
        "This headache must be a brain tumor; there's no other explanation.",
        "I will fail my interview, get rejected, and never find a job in my field.",
        "My anxiety is so bad that I'll have a breakdown and end up in the hospital.",
        "Everything I touch turns into a disaster; I am a walking catastrophe.",
        "If my boss doesn't reply to my email immediately, I assume they hate me and I will get fired tomorrow."
    ],
    "avoidance": [
        "I can't face this right now, I'll just deal with it next week.",
        "I am going to ignore their messages because I don't want to have a difficult conversation.",
        "I'll just stay in bed and watch TV to avoid thinking about my responsibilities.",
        "It's easier to pretend the problem doesn't exist than to try and solve it.",
        "I am too tired to handle this today; I'll postpone it indefinitely.",
        "I am skipping the meeting because I feel too anxious to attend.",
        "I'd rather cancel the plans and stay home where it's safe.",
        "I am going to distract myself with video games so I don't have to worry about my work.",
        "Every time I think about that task, I immediately switch to doing something else.",
        "I am avoiding calling them because I am afraid of what they might say.",
        "I'll just let them make the decision so I don't have to take responsibility.",
        "I am going to sleep instead of finishing this assignment.",
        "I don't want to talk about it, let's change the subject.",
        "I am keeping to myself because interacting with people is too exhausting.",
        "I'll just wait and see if the issue goes away on its own.",
        "I am putting off this doctor's appointment because I don't want to know if something is wrong.",
        "I'd rather walk away from this conflict than try to resolve it.",
        "I am refusing to look at my bank account because I'm scared of how much I spent.",
        "I will do anything else right now except clean my room or do my taxes.",
        "I am hiding from my feelings by keeping myself constantly busy with minor tasks.",
        "I'd rather quit the class than have to give a presentation.",
        "I am avoiding going to the gym because I am afraid people will judge me.",
        "I'll pretend everything is fine so I don't have to deal with the reality.",
        "I am staying silent during the discussion to avoid any potential arguments.",
        "I'll push this task to tomorrow, and then to the next day, and the next.",
        "I am ignoring my emails and phone messages because facing them makes me too anxious."
    ],
    "rumination": [
        "Why do I always make these stupid mistakes? What is wrong with me?",
        "I keep replaying that conversation in my head over and over again, wishing I had said something else.",
        "Why does everything have to be so difficult for me compared to everyone else?",
        "I can't stop thinking about how much they hurt me in the past.",
        "I am constantly analyzing why they looked at me that way and what it really meant.",
        "I keep thinking about all the things that could go wrong tomorrow.",
        "Why can't I just let go of these negative thoughts?",
        "I spend hours trying to figure out the exact reason why I feel this way.",
        "I keep obsessing over my failures and flaws, unable to focus on anything else.",
        "Why am I so weak? Why can't I handle stress like a normal person?",
        "I am stuck in a loop of thinking about my past decisions and how they ruined my life.",
        "I keep thinking about the worst moments of my childhood.",
        "I am constantly questioning my own motives and thoughts.",
        "Why do bad things always happen to me? What did I do to deserve this?",
        "I keep wondering if they were lying to me when they said everything is fine.",
        "I can't quiet my mind; it just keeps running through all my anxieties.",
        "I keep analyzing my feelings to see if my depression or anxiety is returning.",
        "Why am I so stuck? Why can't I make progress like my peers?",
        "I am constantly reviewing my past interactions to see if I made a fool of myself.",
        "I keep dwelling on the fact that I don't know what the future holds.",
        "Why does nobody understand how hard this is for me?",
        "I keep thinking about how unfair my situation is.",
        "I am paralyzed by thinking about all the choices I have to make.",
        "I spend my whole evening overthinking a single comment my boss made.",
        "I can't stop worrying about whether I made the right decision.",
        "Why did I say that? I keep overthinking and analyzing that meeting/conversation for hours, replaying every single word."
    ],
    "perfectionism": [
        "If it is not absolutely perfect, it is a complete failure.",
        "I must get a perfect score on this test, otherwise I am not smart enough.",
        "I can't submit this work yet, it's still not good enough and needs more edits.",
        "I feel like a failure if I make even the smallest mistake.",
        "I have to do everything myself because nobody else can do it to my standards.",
        "I am setting extremely high goals for myself, and I feel devastated if I don't reach them.",
        "I spend hours formatting this document to make sure every pixel is aligned.",
        "I can't enjoy my achievements because I feel like I could have done better.",
        "I am terrified of people seeing my work unless it is completely flawless.",
        "I must never show any signs of weakness or vulnerability.",
        "If I need help, it means I am incompetent and weak.",
        "I am constantly comparing myself to others and feeling like I fall short of perfection.",
        "I would rather not try at all than do a mediocre job.",
        "I am extremely critical of myself when my performance is less than outstanding.",
        "Everything in my life must be perfectly organized and under control.",
        "I feel anxious and uneasy if my routine is disrupted even slightly.",
        "I must always look put-together and successful to the outside world.",
        "My self-worth is entirely dependent on my productivity and achievements.",
        "I can't relax because there is always something I could be improving or doing better.",
        "I beat myself up for days over a minor typo in an email.",
        "I feel like I have to be the best at everything I attempt.",
        "I refuse to settle for anything less than perfection in my work, relationships, and appearance.",
        "I hold others to the same extremely high standards that I hold myself to.",
        "I am constantly editing and rewriting my posts to make sure they sound smart.",
        "A 95% is not good enough; it should have been 100%.",
        "If my work is not absolutely flawless, it is complete garbage. I cannot accept anything less than 100%.",
        "I cannot allow anyone to see my draft or work if there is even a single minor mistake or spelling error.",
        "If my report has even one spelling mistake, they will think I'm an idiot and incompetent."
    ],
    "self_criticism": [
        "I am so stupid and worthless; I can't do anything right.",
        "It's entirely my fault that things went wrong; I should have known better.",
        "I am a terrible person and I don't deserve to be happy.",
        "I hate the way I look and the way I act; I am just embarrassing.",
        "Nobody actually likes me; they are just pretending to be nice out of pity.",
        "I am such a disappointment to my family and friends.",
        "I am weak, lazy, and have no self-discipline whatsoever.",
        "I don't deserve the good things that happen to me; I am just lucky.",
        "I am a failure in every aspect of my life: career, health, and relationships.",
        "I should be stronger and not let things get to me like this.",
        "I am completely useless and add no value to anyone's life.",
        "I am always the one who ruins things.",
        "I am too sensitive and overreact to everything.",
        "I don't belong here; I am a fraud and everyone knows it.",
        "I am not good enough and I never will be.",
        "I should have worked harder; my laziness is the reason I failed.",
        "I am a burden to everyone around me.",
        "I can't even handle simple daily tasks; I am pathetic.",
        "I am ashamed of who I am.",
        "I'll never succeed because I simply don't have what it takes.",
        "I am constantly letting myself and others down.",
        "I am completely unlovable and broken beyond repair.",
        "I hate my own mind and how anxious I get.",
        "I am my own worst enemy; I destroy my own happiness.",
        "I am just a waste of space and time.",
        "I blame myself entirely for this mess. I am just a stupid, lazy, and useless person."
    ]
}

os.makedirs("patterns", exist_ok=True)
for name, examples in patterns.items():
    filepath = os.path.join("patterns", f"{name}.json")
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(examples, f, indent=2)
    print(f"Generated {filepath} with {len(examples)} examples.")
