from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import os
from datetime import datetime

# Sentia Theme Colors
COLOR_BG_DARK = colors.HexColor("#0b0b0b")
COLOR_ACCENT = colors.HexColor("#e1ff5e") # Neon Green
COLOR_TEXT_MAIN = colors.HexColor("#ffffff") # For dark backgrounds
COLOR_TEXT_DARK = colors.HexColor("#1a1a1a") # For light backgrounds
COLOR_HEADER_BG = colors.HexColor("#1a1a1a")

def header_footer(canvas, doc):
    canvas.saveState()
    
    # --- Header ---
    # Logo
    logo_path = "assets/logo.png"
    # Adjust path if running from backend root
    if not os.path.exists(logo_path):
        # Try absolute path based on known structure if relative fails
        # Assuming script runs from backend root
        pass

    if os.path.exists(logo_path):
        # Draw logo at top left
        # Maintain aspect ratio. Height approx 40px
        canvas.drawInlineImage(logo_path, doc.leftMargin, A4[1] - 50, height=40, preserveAspectRatio=True)
    
    # Title
    canvas.setFont("Helvetica-Bold", 16)
    canvas.setFillColor(colors.black)
    canvas.drawRightString(A4[0] - doc.rightMargin, A4[1] - 35, "Emotion Analysis Report")
    
    # Separator Line
    canvas.setStrokeColor(colors.black)
    canvas.setLineWidth(1)
    canvas.line(doc.leftMargin, A4[1] - 60, A4[0] - doc.rightMargin, A4[1] - 60)
    
    # --- Footer ---
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    page_num = canvas.getPageNumber()
    text = f"Page {page_num} | Generated by Sentia AI"
    canvas.drawCentredString(A4[0] / 2, 30, text)
    
    canvas.restoreState()

def generate_pdf(user_id, charts, date_range, report_id):
    os.makedirs("storage/reports", exist_ok=True)
    output_path = f"storage/reports/{report_id}.pdf"

    # Minimal margins to allow header/footer space
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=50, leftMargin=50,
        topMargin=80, bottomMargin=60
    )

    Story = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    style_section_header = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.black,
        spaceBefore=20,
        spaceAfter=10,
        borderPadding=(0, 0, 5, 0), # padding bottom
        borderColor=COLOR_ACCENT,
        borderWidth=2,
        borderRadius=None
    )
    
    style_normal = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#333333")
    )

    # Date / User Info Block
    # Handle ISO format dates safely
    try:
        from_date = datetime.fromisoformat(date_range[0].replace('Z', '+00:00')).strftime("%B %d, %Y")
        to_date = datetime.fromisoformat(date_range[1].replace('Z', '+00:00')).strftime("%B %d, %Y")
    except:
        from_date = str(date_range[0])
        to_date = str(date_range[1])
    
    info_data = [
        [Paragraph(f"<b>Report For:</b> {user_id}", style_normal), 
         Paragraph(f"<b>Period:</b> {from_date} - {to_date}", ParagraphStyle('RightAlign', parent=style_normal, alignment=TA_RIGHT))]
    ]
    t_info = Table(info_data, colWidths=[A4[0]/2 - 55, A4[0]/2 - 55])
    Story.append(t_info)
    Story.append(Spacer(1, 20))

    # --- Executive Summary ---
    Story.append(Paragraph("Executive Summary", style_section_header))
    
    dominant_emotion = charts.get("dominant_emotion", "N/A")
    if dominant_emotion:
        dominant_emotion = dominant_emotion.title()
        
    summary_styled_data = [
        ["METRIC", "VALUE"],
        ["Total Interactions", str(charts.get("total_logs", 0))],
        ["Dominant Emotion", dominant_emotion],
        ["Average Confidence", f"{charts.get('average_confidence', 0) * 100:.1f}%"]
    ]
    
    t_sum = Table(summary_styled_data, colWidths=[200, 150])
    t_sum.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.black),
        ('TEXTCOLOR', (0, 0), (-1, 0), COLOR_ACCENT), # Neon text on black header
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'), # Bold Metrics
    ]))
    Story.append(t_sum)
    Story.append(Spacer(1, 25))

    # --- Charts Section ---
    Story.append(Paragraph("Emotional Trends & Distribution", style_section_header))
    
    # Check if charts exist
    has_charts = False
    
    # 1. Distribution Chart
    if os.path.exists(charts.get("distribution_chart", "")):
        im = Image(charts["distribution_chart"], width=400, height=250)
        Story.append(im)
        Story.append(Paragraph("Fig 1. Distribution of detected emotions over the selected period.", style_normal))
        Story.append(Spacer(1, 20))
        has_charts = True
        
    # 2. Add Timeline chart if available (assuming it was generated in chart_builder)
    # The 'charts' dict usually contains paths. Check for it.
    if os.path.exists(charts.get("timeline_chart", "")):
        im2 = Image(charts["timeline_chart"], width=450, height=200)
        Story.append(im2)
        Story.append(Paragraph("Fig 2. Emotional intensity trends over time.", style_normal))
        Story.append(Spacer(1, 20))
        has_charts = True

    if not has_charts:
        Story.append(Paragraph("No visual charts available for this dataset.", style_normal))
        Story.append(Spacer(1, 20))

    # --- Drift Analysis ---
    Story.append(Paragraph("Drift Alerts (Significant Shifts)", style_section_header))
    
    alerts = charts.get("alerts", [])
    if alerts:
        alert_data = [["Timestamp", "Severity", "Shift Detected"]]
        for a in alerts[:8]: # Limit to 8 to fit page
            time_str = a.created_at.strftime("%Y-%m-%d %H:%M")
            shift = f"{a.from_emotion.title()} -> {a.to_emotion.title()}"
            severity_label = "High" if a.severity >= 0.7 else "Moderate"
            alert_data.append([time_str, severity_label, shift])
            
        t_alerts = Table(alert_data, colWidths=[150, 100, 200])
        t_alerts.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.black),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('LINEBELOW', (0, 0), (-1, 0), 2, COLOR_ACCENT), # Accent line under header
        ]))
        Story.append(t_alerts)
    else:
        Story.append(Paragraph("No significant emotional drift alerts detected in this period.", style_normal))

    # Detailed Distribution Table at the end
    Story.append(Spacer(1, 20))
    dist = charts.get("distribution", {})
    if dist:
        Story.append(Paragraph("Detailed Breakdown", style_section_header))
        dist_data = [["Emotion", "Count", "Percentage"]]
        total = charts.get("total_logs", 1)
        if total == 0: total = 1
        
        for emotion, count in dist.items():
            percentage = (count / total) * 100
            dist_data.append([emotion.title(), str(count), f"{percentage:.1f}%"])
            
        t_dist = Table(dist_data, colWidths=[150, 100, 100])
        t_dist.setStyle(TableStyle([
             ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
             ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
             ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ]))
        Story.append(t_dist)

    # Build PDF with Header/Footer
    doc.build(Story, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_path
