from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import os
from datetime import datetime

# Cinematic Neural VIP Theme Colors
COLOR_BG_DARK = colors.HexColor("#0f172a") # Slate 900
COLOR_ACCENT = colors.HexColor("#38bdf8") # Sky 400 (Electric Blue)
COLOR_TEXT_MAIN = colors.HexColor("#f8fafc") # Slate 50
COLOR_TEXT_DARK = colors.HexColor("#334155") # Slate 700
COLOR_HEADER_BG = colors.HexColor("#1e293b") # Slate 800
COLOR_LIGHT_BG = colors.HexColor("#f1f5f9") # Slate 100

def header_footer(canvas, doc):
    canvas.saveState()
    
    # --- Header ---
    # Logo
    logo_path = "assets/logo.png"
    # Adjust path if running from backend root
    if not os.path.exists(logo_path):
        # Try absolute path based on known structure if relative fails
        # Assuming script runs from backend root
        pass

    if os.path.exists(logo_path):
        # Draw logo at top left
        # Maintain aspect ratio. Height approx 40px
        canvas.drawInlineImage(logo_path, doc.leftMargin, A4[1] - 50, height=40, preserveAspectRatio=True)
    
    # Title
    canvas.setFont("Helvetica-Bold", 18)
    canvas.setFillColor(COLOR_TEXT_DARK)
    canvas.drawRightString(A4[0] - doc.rightMargin, A4[1] - 35, "Cognitive Emotion Analysis")
    
    # Separator Line
    canvas.setStrokeColor(COLOR_ACCENT)
    canvas.setLineWidth(1.5)
    canvas.line(doc.leftMargin, A4[1] - 55, A4[0] - doc.rightMargin, A4[1] - 55)
    
    # --- Footer ---
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    page_num = canvas.getPageNumber()
    text = f"Page {page_num} | Generated by Sentia AI"
    canvas.drawCentredString(A4[0] / 2, 30, text)
    
    canvas.restoreState()

def generate_pdf(user_id, charts, date_range, report_id, conditions=[]):
    os.makedirs("storage/reports", exist_ok=True)
    output_path = f"storage/reports/{report_id}.pdf"

    # Minimal margins to allow header/footer space
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=50, leftMargin=50,
        topMargin=80, bottomMargin=60
    )

    Story = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    style_section_header = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=15,
        textColor=COLOR_TEXT_DARK,
        spaceBefore=24,
        spaceAfter=12,
        borderPadding=(0, 0, 4, 0), # padding bottom
        borderColor=COLOR_ACCENT,
        borderWidth=1.5,
        borderRadius=None
    )
    
    style_normal = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#333333")
    )

    # Date / User Info Block
    # Handle ISO format dates safely
    try:
        from_date = datetime.fromisoformat(date_range[0].replace('Z', '+00:00')).strftime("%B %d, %Y")
        to_date = datetime.fromisoformat(date_range[1].replace('Z', '+00:00')).strftime("%B %d, %Y")
    except:
        from_date = str(date_range[0])
        to_date = str(date_range[1])
    
    info_data = [
        [Paragraph(f"<b>Report For:</b> {user_id}", style_normal), 
         Paragraph(f"<b>Period:</b> {from_date} - {to_date}", ParagraphStyle('RightAlign', parent=style_normal, alignment=TA_RIGHT))]
    ]
    t_info = Table(info_data, colWidths=[A4[0]/2 - 55, A4[0]/2 - 55])
    Story.append(t_info)
    Story.append(Spacer(1, 20))

    # --- Executive Summary ---
    Story.append(Paragraph("Executive Summary", style_section_header))
    
    dominant_emotion = charts.get("dominant_emotion", "N/A")
    if dominant_emotion:
        dominant_emotion = dominant_emotion.title()
        
    summary_styled_data = [
        ["METRIC", "VALUE"],
        ["Total Interactions", str(charts.get("total_logs", 0))],
        ["Dominant Emotion", dominant_emotion],
        ["Average Confidence", f"{charts.get('average_confidence', 0) * 100:.1f}%"]
    ]
    
    t_sum = Table(summary_styled_data, colWidths=[200, 150])
    t_sum.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_HEADER_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), COLOR_ACCENT), # Electric text on slate header
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('PADDING', (0, 0), (-1, -1), 12),
        ('BACKGROUND', (0, 1), (-1, -1), COLOR_LIGHT_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'), # Bold Metrics
        ('TEXTCOLOR', (0, 1), (-1, -1), COLOR_TEXT_DARK),
    ]))
    Story.append(t_sum)
    Story.append(Spacer(1, 25))

    # --- Charts Section ---
    Story.append(Paragraph("Emotional Trends & Distribution", style_section_header))
    
    # Check if charts exist
    has_charts = False
    
    # 1. Distribution Chart
    if os.path.exists(charts.get("distribution_chart", "")):
        im = Image(charts["distribution_chart"], width=400, height=250)
        Story.append(im)
        Story.append(Paragraph("Fig 1. Distribution of detected emotions over the selected period.", style_normal))
        Story.append(Spacer(1, 20))
        has_charts = True
        
    # 2. Add Timeline chart if available (assuming it was generated in chart_builder)
    # The 'charts' dict usually contains paths. Check for it.
    if os.path.exists(charts.get("timeline_chart", "")):
        im2 = Image(charts["timeline_chart"], width=450, height=200)
        Story.append(im2)
        Story.append(Paragraph("Fig 2. Emotional intensity trends over time.", style_normal))
        Story.append(Spacer(1, 20))
        has_charts = True

    if not has_charts:
        Story.append(Paragraph("No visual charts available for this dataset.", style_normal))
        Story.append(Spacer(1, 20))

    # --- Drift Analysis ---
    Story.append(Paragraph("Drift Alerts (Significant Shifts)", style_section_header))
    
    alerts = charts.get("alerts", [])
    if alerts:
        alert_data = [["Timestamp", "Severity", "Shift Detected"]]
        for a in alerts[:8]: # Limit to 8 to fit page
            time_str = a.created_at.strftime("%Y-%m-%d %H:%M")
            shift = f"{a.from_emotion.title()} -> {a.to_emotion.title()}"
            severity_label = "High" if a.severity >= 0.7 else "Moderate"
            alert_data.append([time_str, severity_label, shift])
            
        t_alerts = Table(alert_data, colWidths=[150, 100, 200])
        t_alerts.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), COLOR_HEADER_BG),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [COLOR_LIGHT_BG, colors.white]),
            ('TEXTCOLOR', (0, 1), (-1, -1), COLOR_TEXT_DARK),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('PADDING', (0, 0), (-1, -1), 10),
            ('LINEBELOW', (0, 0), (-1, 0), 2, COLOR_ACCENT), # Accent line under header
        ]))
        Story.append(t_alerts)
    else:
        Story.append(Paragraph("No significant emotional drift alerts detected in this period.", style_normal))

    # Detailed Distribution Table at the end
    Story.append(Spacer(1, 20))
    dist = charts.get("distribution", {})
    if dist:
        Story.append(Paragraph("Detailed Breakdown", style_section_header))
        dist_data = [["Emotion", "Count", "Percentage"]]
        total = charts.get("total_logs", 1)
        if total == 0: total = 1
        
        for emotion, count in dist.items():
            percentage = (count / total) * 100
            dist_data.append([emotion.title(), str(count), f"{percentage:.1f}%"])
            
        t_dist = Table(dist_data, colWidths=[150, 100, 100])
        t_dist.setStyle(TableStyle([
             ('BACKGROUND', (0, 0), (-1, 0), COLOR_HEADER_BG),
             ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
             ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
             ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
             ('ROWBACKGROUNDS', (0, 1), (-1, -1), [COLOR_LIGHT_BG, colors.white]),
             ('TEXTCOLOR', (0, 1), (-1, -1), COLOR_TEXT_DARK),
             ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
             ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        Story.append(t_dist)

    # --- Condition Pattern Analysis ---
    Story.append(Paragraph("Condition Pattern Analysis (Beta)", style_section_header))
    
    if conditions:
        Story.append(Paragraph("<b>Note:</b> The following patterns were detected based on emotional frequency and stability. This is NOT a diagnosis.", style_normal))
        Story.append(Spacer(1, 10))
        
        for c in conditions:
            # Color code based on level
            level_color = colors.green
            if c['level'] == 'Moderate': level_color = colors.orange
            if c['level'] == 'High': level_color = colors.red
            
            # Condition Header
            p_text = f"<b>{c['name']}</b> - <font color={level_color}>{c['level']} Risk</font>"
            Story.append(Paragraph(p_text, style_normal))
            
            # Description
            Story.append(Paragraph(f"<i>{c['description']}</i>", style_normal))
            
            # Recommendation
            rec_text = f"<b>Recommendation:</b> {c['recommendation']}"
            Story.append(Paragraph(rec_text, style_normal))
            
            Story.append(Spacer(1, 10))
    else:
        Story.append(Paragraph("No specific adverse condition patterns detected in this period.", style_normal))

    Story.append(Spacer(1, 20))

    # --- Mental Health Resources & Disclaimer ---
    Story.append(PageBreak())
    Story.append(Paragraph("Mental Health Resources & Important Disclaimer", style_section_header))
    
    disclaimer_text = """
    <b>Disclaimer:</b> This report is generated by an AI system (Sentia) based on analyzing your text and facial expressions. 
    It is <b>NOT</b> a medical diagnosis. The trends shown here are for informational purposes only (self-reflection). 
    If you are feeling overwhelmed, depressed, or having thoughts of self-harm, please contact a professional immediately.
    """
    Story.append(Paragraph(disclaimer_text, style_normal))
    Story.append(Spacer(1, 15))
    
    resources_data = [
        ["Resource", "Contact / Details"],
        ["Tele-MANAS (India)", "14416 (24x7 Free Support)"],
        ["Vandrevala Foundation", "9999 666 555"],
        ["iCall (TISS)", "9152987821"],
        ["Emergency", "112 (National Emergency Number)"]
    ]
    
    t_res = Table(resources_data, colWidths=[200, 250])
    t_res.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_HEADER_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), COLOR_ACCENT),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 1), (-1, -1), COLOR_LIGHT_BG),
        ('TEXTCOLOR', (0, 1), (-1, -1), COLOR_TEXT_DARK),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 12),
    ]))
    Story.append(t_res)

    # Build PDF with Header/Footer
    doc.build(Story, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_path
